import { ProgramIconName } from '@/types/workout';

export const PROGRAM_ICON_OPTIONS: { icon: ProgramIconName; labelKey: string }[] = [
  { icon: 'barbell-outline', labelKey: 'programIcons.barbell' },
  { icon: 'fitness-outline', labelKey: 'programIcons.fitness' },
  { icon: 'body-outline', labelKey: 'programIcons.body' },
  { icon: 'flash-outline', labelKey: 'programIcons.power' },
  { icon: 'flame-outline', labelKey: 'programIcons.intense' },
  { icon: 'trophy-outline', labelKey: 'programIcons.goal' },
  { icon: 'walk-outline', labelKey: 'programIcons.walk' },
  { icon: 'bicycle-outline', labelKey: 'programIcons.bike' },
  { icon: 'football-outline', labelKey: 'programIcons.football' },
  { icon: 'basketball-outline', labelKey: 'programIcons.basketball' },
  { icon: 'tennisball-outline', labelKey: 'programIcons.tennis' },
  { icon: 'golf-outline', labelKey: 'programIcons.golf' },
  { icon: 'baseball-outline', labelKey: 'programIcons.ball' },
  { icon: 'medal-outline', labelKey: 'programIcons.medal' },
  { icon: 'heart-outline', labelKey: 'programIcons.health' },
  { icon: 'pulse-outline', labelKey: 'programIcons.pulse' },
  { icon: 'speedometer-outline', labelKey: 'programIcons.speed' },
  { icon: 'timer-outline', labelKey: 'programIcons.time' },
  { icon: 'stopwatch-outline', labelKey: 'programIcons.stopwatch' },
  { icon: 'water-outline', labelKey: 'programIcons.water' },
  { icon: 'nutrition-outline', labelKey: 'programIcons.nutrition' },
  { icon: 'moon-outline', labelKey: 'programIcons.night' },
  { icon: 'sunny-outline', labelKey: 'programIcons.morning' },
  { icon: 'shield-checkmark-outline', labelKey: 'programIcons.shield' },
];
